# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"
tasks:
  format:
    cmd: stylua .
    silent: true
  test:
    cmd: nvim --headless -u NONE -l tests/run.lua
    silent: true
  typecheck:
    cmd: lua-language-server --check=. --checklevel=Warning
    silent: true
